/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Reservation = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'specialRequests' : IDL.Text,
  'time' : IDL.Text,
  'submittedAt' : Time,
  'guestName' : IDL.Text,
  'numberOfGuests' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const SubmitReservationRequest = IDL.Record({
  'date' : IDL.Text,
  'specialRequests' : IDL.Text,
  'time' : IDL.Text,
  'guestName' : IDL.Text,
  'numberOfGuests' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'debugGetIsAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitReservation' : IDL.Func([SubmitReservationRequest], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Reservation = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'specialRequests' : IDL.Text,
    'time' : IDL.Text,
    'submittedAt' : Time,
    'guestName' : IDL.Text,
    'numberOfGuests' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const SubmitReservationRequest = IDL.Record({
    'date' : IDL.Text,
    'specialRequests' : IDL.Text,
    'time' : IDL.Text,
    'guestName' : IDL.Text,
    'numberOfGuests' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'debugGetIsAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitReservation' : IDL.Func([SubmitReservationRequest], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };